name: ppo
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - gymnasium
  - pybullet
  - matplotlib
  - pandas
  - pip:
      - stable-baselines3==2.1.0
      - cloudpickle
      - tqdm

