name: ppo
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - numpy
  - pytorch=2.3.0
  - torchvision=0.18.1
  - torchaudio=2.3.0
  - pytorch-cuda=12.1
  - gymnasium
  - stable-baselines3
  - pybullet
  - matplotlib
  - pandas
  - tqdm
  - tensorboard
  - pip:
      - bigtree
      - cloudpickle
      - attrdict
      - shimmy

